export async function gerateMetadata() {
  return {
    title: "New Project | Human Rights Tool",
    description: "Generated by create next app",
  };
}

export default function ProjectsPage() {
  return "new";
}
