import { Metadata } from "next";

export const metadata: Metadata = {
  title: "New Project | Human Rights Tool",
  description: "Generated by create next app",
};

export default function ProjectsNewPage() {
  return "new";
}
