import { Metadata } from "next";

import ProjectsNew from "@/containers/projects/new";

export const metadata: Metadata = {
  title: "New Project | Human Rights Screening Tool",
  description: "Generated by create next app",
};

export default function ProjectsNewPage() {
  return <ProjectsNew />;
}
