import { Metadata } from "next";

import Projects from "@/containers/projects";

export const metadata: Metadata = {
  title: "Projects | Human Rights Tool",
  description: "Generated by create next app",
};

export default function ProjectsPage() {
  return <Projects />;
}
