import { Metadata } from "next";

type ProjectsDetailPageProps = {
  params: {
    id: string;
  };
};

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default function ProjectsDetailPage() {
  return "id";
}
