import { Metadata } from "next";

import Link from "next/link";

export type ProjectsDetailPageProps = {
  params: {
    id: string;
  };
};

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default function ProjectsDetailPage({ params }: ProjectsDetailPageProps) {
  return (
    <div>
      <Link href={`/projects/${params.id}/project-and-background-community`}>Start</Link>
    </div>
  );
}
