export async function gerateMetadata() {
  return {
    title: "[id] | Human Rights Tool",
    description: "Generated by create next app",
  };
}

export default function ProjectsPage() {
  return "id";
}
