import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign up | Human Rights Tool",
  description: "Generated by create next app",
};

export default function SignupPage() {
  return (
    <section className="flex grow flex-col items-center justify-center space-y-5 p-24">
      {/* <Signin /> */}
      Signup
    </section>
  );
}
