import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { ProjectsDetailPageProps } from "@/app/(app)/projects/[id]/page";

import FollowUpSidebar from "@/containers/projects/detail/sidebar/follow-up";
import Sidebar from "@/containers/sidebar";

interface ProjectsDetailFollowUpLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | FollowUp | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailFollowUpLayout({
  children,
}: ProjectsDetailFollowUpLayoutProps) {
  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12 gap-20">
        <div className="col-span-4">
          <Sidebar>
            <FollowUpSidebar />
          </Sidebar>
        </div>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
