import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { Hydrate, dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/lib/getQueryClient";

import { getGetPcbsQueryOptions } from "@/types/generated/pcb";
import {
  getGetPcbCategoriesIdQueryOptions,
  getPcbCategories,
} from "@/types/generated/pcb-category";

import { ProjectsDetailPageProps } from "@/app/[locale]/(app)/projects/[id]/page";

import PcbSidebar from "@/containers/projects/detail/sidebar/pcb";
import Sidebar from "@/containers/sidebar";

interface ProjectsDetailPCBLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | PCB | Human Rights Screening Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailPCBLayout({ children }: ProjectsDetailPCBLayoutProps) {
  const CATEGORIES = await getPcbCategories({
    sort: "display_order:asc",
  });

  // prefetch category id data
  const queryClient = getQueryClient();

  for (const c of CATEGORIES?.data ?? []) {
    if (!c.id) return;
    await queryClient.prefetchQuery(getGetPcbCategoriesIdQueryOptions(c.id));
    await queryClient.prefetchQuery(
      getGetPcbsQueryOptions({
        filters: {
          pcb_category: c.id,
        },
        populate: "*",
      }),
    );
  }

  const dehydratedState = dehydrate(queryClient);

  return (
    <Hydrate state={dehydratedState}>
      <section className="flex grow flex-col space-y-5">
        <div className="grid grid-cols-12 gap-20">
          <div className="col-span-4">
            <Sidebar>
              <PcbSidebar />
            </Sidebar>
          </div>
          <div className="col-span-8">{children}</div>
        </div>
      </section>
    </Hydrate>
  );
}
