import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { ProjectsDetailPageProps } from "@/app/[locale]/(app)/projects/[id]/page";

import ProjectRiskSidebar from "@/containers/projects/detail/sidebar/project-risk";
import Sidebar from "@/containers/sidebar";

interface ProjectsDetailProjectRiskLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | ProjectRisk | Human Rights Screening Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailProjectRiskLayout({
  children,
}: ProjectsDetailProjectRiskLayoutProps) {
  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12 gap-20">
        <div className="col-span-4">
          <Sidebar>
            <ProjectRiskSidebar />
          </Sidebar>
        </div>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
