<!-- eslint-disable vue/valid-template-root -->
<template>

        <!-- Overview text -->
        <div class="overview">
          <h2>Follow Up Overview</h2>

          <h4>
            Save and Share link for now, until we know where to put it (anyone
            with link can view, even outside TNC)
          </h4>
          <a :href="saveAndShareLink" target="_blank">{{ saveAndShareLink }}</a>
          <br />
          <!-- <span
            v-html="activeCategory.description"
            class="indicator-description"
          ></span> -->
          <p>To be inserted from CMS after editing is finished</p>
          <p>
            The screening process extracts key summary information about each
            potential project risk; this information is then tabled on the
            Escalate, Priority, and Watch Lists generated by the process. These
            results tables can be used by teams to organize and proceed to take
            action per the different recommendations of each List. (Note that
            the Tool is designed to eventually be transformed into a web-based
            interactive format; this format will be able to auto-generate the
            results tables with responsive information as well as generate other
            types of reports for efficient review.)
          </p>
        </div>

        <p>
          Note that the flexibility of the Project Risk Determination and the
          potentially overlapping multiple lists are intentionally designed to
          leave project teams have substantial discretion to set priorities and
          schedule issues for analysis and attention at different stages in
          project design and implementation. The process thus aims to ensure
          transparency and accountability, while also respecting the importance
          of local management and expertise in project development, especially
          in managing relationships with Communities.
        </p>

        <p>Insert dynamic button</p>

        <!-- User inputs -->
        <!-- <div
        class="grid indicator-row"
        v-for="(item, index) in activeIndicators"
        :key="item.id"
      >
        <div class="col-12 sm:col-12 md:col-12 lg:col-7 xl:col-7">
          <h3>{{ item.indicator_id }} {{ item.title }}</h3>
          <span v-html="item.description"></span>
        </div>
        <div class="col-12 sm:col-12 md:col-12 lg:col-5 xl:col-5">
          <div class="indicator-options">
          </div>
        </div>
      </div> -->

        <!-- Need to right-align next button. Probably should do this with flex box -->

        <!-- <div class="next-section">
          <p>
            <em>Next: {{ nextSection.title }}</em>
            <router-link :to="nextSection.category_slug">
              <Button
                label="Next Section"
                class="p-button-sm next-button"
                @click="scrollToTop"
              />
            </router-link>
          </p>
        </div> -->

</template>

<script setup>
import { ref, computed } from 'vue';
import { useRoute } from 'vue-router';
import { useHrtStore } from '../../store/hrtStore';

import RadioButton from 'primevue/radiobutton';
import Button from 'primevue/button';
import Textarea from 'primevue/textarea';
import TheSideNav from '../layout/TheSideNav.vue';

const hrtStore = useHrtStore();
const route = useRoute();

console.log(window.location.origin + '/report?sid=' + hrtStore.sessionId);

const saveAndShareLink = ref(
  window.location.origin + '/report?sid=' + hrtStore.sessionId
);

const activeCategory = computed(() => {
  try {
    let categories = hrtStore.indicatorCategories;
    let category_id = route.params.category_id;

    let filteredCategory = categories.filter(
      (category) => category.category_slug === category_id
    );
    return filteredCategory[0];
  } catch (error) {
    console.log('error');
    return { title: '' };
  }
});

const activeIndicators = computed(() => {
  let indicators = hrtStore.indicators;
  let category_id = route.params.category_id;

  let filteredIndicators = indicators.filter(
    (indicator) => indicator.category_slug === category_id
  );

  let sortedIndicators = filteredIndicators.sort((a, b) =>
    a['indicator_id'].localeCompare(b['indicator_id'], undefined, {
      numeric: true,
    })
  );

  return sortedIndicators;
});

const nextSection = computed(() => {
  let categories = hrtStore.indicatorCategories;
  let categoryId = route.params.category_id;
  let categoryCount = hrtStore.indicatorCategories.length;

  let filteredCategoryId = categories.filter(
    (category) => category.category_slug === categoryId
  )[0].display_order;

  let nextId = filteredCategoryId;

  if (categoryCount > nextId) {
    return categories[filteredCategoryId];
  } else {
    return { category_slug: '' };
  }
});

const pageTop = ref(null);

const scrollToTop = () => {
  pageTop.value?.scrollIntoView({ behavior: 'smooth', block: 'center' });
};
</script>

<style scoped>
h2 {
  margin-bottom: 10px;
  margin-top: 15px;
}
h3 {
  margin: 0 0 0px !important;
  padding-bottom: 0;
}
p {
  margin: 0 0 20px !important;
  padding-top: 0;
  padding-right: 40px;
  color: #444;
}
li {
  color: #444;
}

a {
  text-decoration: none;
}
.container {
  margin: 20px 30px;
}
.screen-body {
  background: white;
  border: 1px solid #ccc;
  padding: 20px 20px !important;
  margin-bottom: 20px;
}
.screen-body p {
  margin-bottom: 0;
}
.overview {
  background: #ecf7fa;
  padding: 10px 20px 10px;
  margin-bottom: 20px;
  /* width: 90%; */
}
.overview p {
  font-size: 18px;
  font-style: italic;
  line-height: 1.5em;
  margin-bottom: 20px;
}

.indicator-row {
  margin-bottom: 20px;
}
.indicator-options {
  margin-top: 30px;
}
.indicator-notes {
  color: #888;
  font-size: 20px;
  margin-left: 40px;
}
.p-inputtext {
  color: #3b89b6 !important;
}
label {
  margin: 0px 15px 0 5px;
  padding-top: 5px;
  color: #222;
}
.textarea {
  display: block;
  width: 100%;
}
.textarea-label {
  display: block;
  width: 100%;
  color: #444;
  font-weight: bold;
  font-size: 14px;
}

.next-section {
  border-top: 1px solid #ccc;
  padding-top: 20px;
}
.next-button {
  margin-left: 40px !important;
  margin-top: 5px !important;
  background: #38bb93 !important;
}

.p-radiobutton .p-radiobutton-box.p-highlight {
  border-color: #38bb93 !important;
  background: #38bb93 !important;
}

.p-radiobutton .p-radiobutton-box .p-radiobutton-icon {
  background: #4cbadd;
  background: #38bb93 !important;
}

@media screen and (max-width: 1000px) {
  h2 {
    margin-top: 10px;
    margin-bottom: 10px;
  }
  .overview p {
    font-size: 16px;
    padding-right: 0;
    margin-right: 20px;
  }
  .indicator-row p {
    font-size: 15px;
  }
  .indicator-options {
    margin-top: 0px;
  }
  label {
    font-size: 15px;
  }
}
</style>
