import { Metadata } from "next";

import ResetPassword from "@/containers/reset-password";

export const metadata: Metadata = {
  title: "Reset password | Human Rights Screening Tool",
  description: "Generated by create next app",
};

export default function ResetPasswordPage() {
  return (
    <section className="flex grow flex-col items-center justify-center space-y-5 py-24">
      {/* <Signin /> */}
      <ResetPassword />
    </section>
  );
}
