import { Metadata } from "next";

import Signup from "@/containers/signup";

export const metadata: Metadata = {
  title: "Sign up | Human Rights Screening Tool",
  description: "Generated by create next app",
};

export default function SignupPage() {
  return (
    <section className="flex grow flex-col items-center justify-center space-y-5 py-24">
      {/* <Signin /> */}
      <Signup />
    </section>
  );
}
