import { Metadata } from "next";

import ForgotPassword from "@/containers/forgot-password";

export const metadata: Metadata = {
  title: "Forgot password | Human Rights Tool",
  description: "Generated by create next app",
};

export default function ForgotPasswordPage() {
  return (
    <section className="flex grow flex-col items-center justify-center space-y-5 py-24">
      {/* <Signin /> */}
      <ForgotPassword />
    </section>
  );
}
