import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { ProjectsDetailPageProps } from "@/app/projects/[id]/page";

import NavigationSidebar from "@/containers/navigation/sidebar";
import Sidebar from "@/containers/sidebar";

interface ProjectsDetailResearchLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Research | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

const LINKS = [
  {
    href: "/research",
    label: "Overview",
    className: "text-lg",
  },
  // {
  //   href: "/research/iplc",
  //   label: "IPLC",
  // },
  // {
  //   href: "/research/gender-and-vulnerable-groups",
  //   label: "Gender & Vulnerable Groups",
  // },
  // {
  //   href: "/research/stakeholders-and-interested-parties",
  //   label: "Stakeholders & Interested Parties",
  // },
  // {
  //   href: "/research/carbon-offset-project-controversies",
  //   label: "Carbon Offset Project Controversies",
  // },
];

export default async function ProjectsDetailResearchLayout({
  children,
  params,
}: ProjectsDetailResearchLayoutProps) {
  const { id } = params;

  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12 gap-20">
        <div className="col-span-4">
          <Sidebar>
            <NavigationSidebar
              items={LINKS.map(({ href, label, className }) => ({
                href: `/projects/${id}${href}`,
                label,
                className,
              }))}
            />
          </Sidebar>
        </div>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
