import type { Metadata } from "next";

import Sidebar from "@/containers/sidebar";
import SidebarLink from "@/containers/sidebar/link";

type ProjectsDetailResearchPageProps = {
  params: {
    id: string;
  };
};

export async function generateMetadata({
  params,
}: ProjectsDetailResearchPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Research | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

const LINKS = [
  {
    href: "/research",
    label: "Overview",
  },
  {
    href: "/research/iplc",
    label: "IPLC",
  },
  {
    href: "/research/gender-and-vulnerable-groups",
    label: "Gender & Vulnerable Groups",
  },
  {
    href: "/research/stakeholders-and-interested-parties",
    label: "Stakeholders & Interested Parties",
  },
  {
    href: "/research/carbon-offset-project-controversies",
    label: "Carbon Offset Project Controversies",
  },
];

export default async function ProjectsDetailResearchLayout({
  children,
  params,
}: {
  children: React.ReactNode;
} & ProjectsDetailResearchPageProps) {
  const { id } = params;

  return (
    <section className="flex grow flex-col space-y-5 py-5">
      <div className="grid grid-cols-12">
        <Sidebar>
          <ul>
            {LINKS.map(({ href, label }) => (
              <li key={href}>
                <SidebarLink href={`/projects/${id}${href}`}>{label}</SidebarLink>
              </li>
            ))}
          </ul>
        </Sidebar>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
