import type { Metadata } from "next";

import Link from "next/link";

type ProjectsDetailResearchPageProps = {
  params: {
    id: string;
  };
};

export async function generateMetadata({
  params,
}: ProjectsDetailResearchPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Research | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailResearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex grow flex-col space-y-5 py-5">
      <div className="grid grid-cols-12">
        <aside className="col-span-4">
          <ul>
            <li>
              <Link href={`/projects/${1}/research`}>Overview</Link>
            </li>
            <li>
              <Link href={`/projects/${1}/research/iplc`}>IPLC</Link>
            </li>
            <li>
              <Link href={`/projects/${1}/research/gender-and-vulnerable-groups`}>
                Gender & Vulnerable Groups
              </Link>
            </li>
          </ul>
        </aside>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
