import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { ProjectsDetailPageProps } from "@/app/projects/[id]/page";

import NavigationSidebar from "@/containers/navigation/sidebar";
import Sidebar from "@/containers/sidebar";

import { getPCBCategories } from "@/data/pcb/categories";

interface ProjectsDetailPCBLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | PCB | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailPCBLayout({
  children,
  params,
}: ProjectsDetailPCBLayoutProps) {
  const { id } = params;

  const CATEGORIES = await getPCBCategories();

  const items = [
    {
      href: `/projects/${id}/project-and-background-community`,
      label: "Overview",
      className: "text-lg",
    },
    ...CATEGORIES.data.map(({ id: categoryId, title }) => ({
      href: `/projects/${id}/project-and-background-community/${categoryId}`,
      label: title,
    })),
  ];

  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12 gap-20">
        <div className="col-span-4">
          <Sidebar>
            <NavigationSidebar items={items} />
          </Sidebar>
        </div>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
