import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { getPcbCategories } from "@/types/generated/pcb-category";

import { ProjectsDetailPageProps } from "@/app/projects/[id]/page";

import NavigationSidebar, { NavigationSidebarProps } from "@/containers/navigation/sidebar";
import NavigationCircle from "@/containers/navigation/sidebar/circle";
import Sidebar from "@/containers/sidebar";

interface ProjectsDetailPCBLayoutProps extends ProjectsDetailPageProps, PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | PCB | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

export default async function ProjectsDetailPCBLayout({
  children,
  params,
}: ProjectsDetailPCBLayoutProps) {
  const { id } = params;

  const CATEGORIES = await getPcbCategories();

  const items = [
    {
      href: `/projects/${id}/project-and-background-community`,
      label: "Overview",
      children: <span className="text-lg">Overview</span>,
    },
    ...(CATEGORIES?.data || [])?.map(({ id: categoryId, attributes }) => {
      const percentage = Math.random();

      return {
        href: `/projects/${id}/project-and-background-community/${categoryId}`,
        label: attributes?.title ?? "",
        children: (
          <>
            <span>{attributes?.title}</span>
            {/* Draw a svg circle that I can control how much of the path is filled */}
            <NavigationCircle percentage={percentage} />
          </>
        ),
      };
    }),
  ] satisfies NavigationSidebarProps["items"];

  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12 gap-20">
        <div className="col-span-4">
          <Sidebar>
            <NavigationSidebar items={items} />
          </Sidebar>
        </div>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
