import { PropsWithChildren } from "react";

import type { Metadata } from "next";

import { ProjectsDetailPageProps } from "@/app/projects/[id]/page";

import NavigationSidebar from "@/containers/navigation/sidebar";
import Sidebar from "@/containers/sidebar";

import CMS from "@/services/cms";

interface ProjectsDetailContextualRiskLayoutProps
  extends ProjectsDetailPageProps,
    PropsWithChildren {}

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | ContextualRisk | Human Rights Tool`,
    description: "Generated by create next app",
  };
}

async function getCategories() {
  return CMS<{
    data: {
      id: string;
      title: string;
    }[];
  }>({
    method: "GET",
    url: "/items/contextual_risk_categories",
  });
}

export default async function ProjectsDetailContextualRiskLayout({
  children,
  params,
}: ProjectsDetailContextualRiskLayoutProps) {
  const { id } = params;

  const CATEGORIES = await getCategories();

  return (
    <section className="flex grow flex-col space-y-5">
      <div className="grid grid-cols-12">
        <Sidebar>
          <NavigationSidebar
            items={CATEGORIES.data.map(({ id: categoryId, title }) => ({
              href: `/projects/${id}/contextual-risk/${categoryId}`,
              label: title,
            }))}
          />
        </Sidebar>
        <div className="col-span-8">{children}</div>
      </div>
    </section>
  );
}
