import { Metadata } from "next";

import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export type ProjectsDetailPageProps = {
  params: {
    id: string;
  };
};

export async function generateMetadata({ params }: ProjectsDetailPageProps): Promise<Metadata> {
  return {
    title: `Project ${params.id} | Human Rights Screening Tool`,
    description: "Generated by create next app",
  };
}

export default function ProjectsDetailPage({ params }: ProjectsDetailPageProps) {
  return (
    <div className="grid grid-cols-12 gap-y-10 lg:gap-20">
      <div className="col-span-12 lg:col-span-8">
        <div className="prose">
          <h2>Human Rights and Conservation</h2>
          <p>
            Successful and lasting conservation should prioritize the human rights, collective
            rights, authority, and capacity of Indigenous Peoples and Local Communities (IPLCs) to
            manage and protect their lands and natural resources.
          </p>

          <ul>
            <li>
              For more details about this approach, see the{" "}
              <a href="https://tncvoicechoiceaction.org/" target="_blank" rel="noopener noreferrer">
                Voice, Choice, and Action Framework.
              </a>
            </li>
            <li>
              For best practices in implementing it, see the{" "}
              <a
                href="https://www.tnchumanrightsguide.org/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Human Rights Guide.
              </a>
            </li>
          </ul>

          <p>
            The term IPLCs comprises all communities and individuals who maintain profound economic
            and cultural connections to the land where they live.
          </p>

          <p>
            IPLCs are <strong>leaders</strong> who have agency over understanding and protecting
            their own rights, not <strong>beneficiaries</strong> whose rights are protected by
            others.
          </p>

          <p>
            The concept of human rights — rights inherent to all humans — resonates across many
            cultures and traditions. And while international human rights laws, as established by
            treaties and in courts, are important and often legally binding, the concept of human
            rights cannot be fully understood through one single perspective.
          </p>

          <p>
            Human rights work therefore respects the principles of non-discrimination,
            accountability, transparency, participation, and the right to self-determination.
            Conservation programs should work with IPLC rightsholders to understand their
            perspectives on the most effective, culturally meaningful ways to uphold human rights.
          </p>

          <p>
            Businesses and organizations can’t outsource their responsibility to respect human
            rights by merely complying with the terms of national law. While businesses and
            organizations must of course comply with the law, its responsibility goes over and above
            that, and requires that conduct complies with international human rights norms.
          </p>

          <p>
            This can be called human rights due diligence. Businesses and organizations are required
            to investigate, assess, and respond to their own impacts and the impact of all partners
            and associates. The scope of impacts includes any to which organizations contribute or
            are directly linked. And while this doesn’t mean the organizations are legally
            responsible for or have complete control over the whole range, it does mean that they
            are bound to use their leverage to mitigate adverse human rights impacts wherever it
            can.
          </p>

          <p>
            This duty of care is embedded in many organizations’ relationships and institutional
            structures and practices. The underlying goals and principles of the conservation and
            human rights agendas must merge, as described, for example, in The Nature Conservancy’s
            VCA Framework(1), Human Rights Guide(2), and other guidance.
          </p>

          <h2>Human Rights and Natural Climate Solutions</h2>
          <p>
            The relationship between human rights and conservation is reciprocal. Human rights can
            only thrive on a livable planet.
          </p>

          <p>
            <a
              href="https://www.pnas.org/doi/10.1073/pnas.1710465114"
              target="_blank"
              rel="noopener noreferrer"
            >
              Natural Climate Solutions
            </a>{" "}
            — a global effort to implement actions that protect, better manage, or restore
            grasslands, croplands, forests, and wetlands to reduce greenhouse gas emissions and
            store carbon.
          </p>

          <p>This work is a critical step to avoid climate catastrophe.</p>

          <p>
            Because NCS is rooted in ecosystem stewardship and not, for example, industrial
            emissions reduction, it can serve as a platform for IPLCs to pursue their own
            self-determined climate agendas. Also, NCS seeks to create income opportunities for
            IPLCs from successful community mitigation projects paid for by global beneficiaries of
            the mitigation.
          </p>

          <p>
            It’s important to know that NCS and other global conservation efforts have occasionally
            been criticized by Indigenous rights advocates for a history of displacements based on
            the{" "}
            <a
              href="https://india.mongabay.com/2021/10/conservation-by-eliminating-human-presence-is-a-flawed-construct-study/"
              target="_blank"
              rel="noopener noreferrer"
            >
              fortress conservation
            </a>{" "}
            mindset. Critics ask whether that mindset still underlies conservation practice today,
            and the perception that NCS is part of the problem rather than part of the solution
            <a
              href="https://news.mongabay.com/2021/10/advocates-call-for-a-new-human-rights-based-approach-to-conservation/"
              target="_blank"
              rel="noopener noreferrer"
            >
              may be growing
            </a>
            .
          </p>
          <p>
            NCS is in the public domain. A few scientists and practitioners collaborated to define
            the concept early on, but no single entity can say definitively what NCS is or is not,
            nor govern the use of the NCS label. The ability to protect the NCS brand is therefore
            limited, and the NCS label is sometimes applied to projects of questionable integrity.
          </p>

          <p>
            Practitioners can help mitigate this issue by defining and demanding integrity as a part
            of their practice. The development and promotion of this Tool can demonstrate commitment
            to the understanding that NCS exists to respect human rights and actively promote
            Indigenous self-determination, human well-being, and equity.
          </p>

          <p>This is no small matter.</p>

          <p>
            Having a responsibility to protect human rights means that the concept of respect is
            deeply embedded in an organization’s relationships, structures, and practices.
          </p>

          <p>
            The full range of rights impacts — encompassing not only severe abuses, but also
            socio-economic rights, labor rights, cultural rights, the right to self-determination,
            the right to participation and benefits, and inter-generational duties — must be
            considered.
          </p>

          <p>This Tool is meant to address the full scope and complexity of this responsibility.</p>

          <h2>Tool Design Considerations</h2>

          <p>
            This is a screening tool to help teams <strong>identify</strong>,{" "}
            <strong>prioritize</strong>, and <strong>analyze</strong> information about the human
            rights impacts of NCS and conservation projects.
          </p>

          <p>
            The Screening Tool returns a series of issue lists (<strong>Research</strong>,{" "}
            <strong>Escalate</strong>, <strong>Prioritize</strong>, and <strong>Watch</strong>) with
            recommended actions for each.
          </p>
          <p>
            Prioritization is an essential element of human rights due diligence. It requires making
            judgment calls and hard decisions. The Project Risk Determination Framework lists
            factors for teams to consider in making these decisions.
          </p>

          <p>
            While the Tool requires and relies primarily on teams’ local knowledge at the screening
            stage, it highlights when more information is needed from Communities, and requires
            Community engagement at the action phase.
          </p>

          <p>The Tool adheres to three sets of competing ambitions:</p>

          <h3>Essential, but not overbearing</h3>
          <p>
            There are benefits to a consistent, globally applicable approach. Yet teams in the field
            have the nuanced understanding necessary to craft culturally meaningful and sustainable
            solutions, and this expertise can’t be subordinated.
          </p>

          <h3>Rigorous, but not incomprehensible. </h3>
          <p>
            A rigorous and professional standard of human rights analysis is a worthy goal. Yet it
            cannot obscure comprehension or the ability of the teams doing the work to practically
            apply the advice and guidance of the analysis.
          </p>

          <h3>Inclusive, but not exhaustive.</h3>
          <p>
            The human rights analysis organization NomoGaia says that the 40 core human rights
            interact in complex ways, meaning that there are “a plethora of theoretically possible,
            small ways that a [project’s] operations can impact them.” Yet when analysis becomes
            overwhelming, it becomes paralyzing. Thorough canvassing of this complexity is
            important, and analytical boundaries and models for determining priorities are likewise
            essential.
          </p>

          <h2>Tool Workshopping Process</h2>
          <p>
            In April 2022, TNC field teams working separately in Indonesia, Kenya, Mexico,
            Australia, Angola, Mongolia, the United States, Guatemala, and Brazil participated in a
            workshop process that included an introduction, a fact-gathering exercise, a tool
            application exercise, and a follow-up interview.
          </p>
          <p>
            In September 2022, one team conducted a full-day application of the Screening Tool,
            which enabled them to fully immerse in the practical realities of using the Tool. This
            helped our team identify new issues and calibrate guidance on how to prioritize issues.
          </p>
          <p>Guidance from all the above work shaped the current iteration of the Tool.</p>
          <p>
            The Tool will continue to adapt to the new lessons of experience as future teams use it.
          </p>

          <h2>The Tool, the Guide, the VCA</h2>
          <p>The Tool’s aims are twofold:</p>
          <ol>
            <li>
              To help teams realize the goals of the{" "}
              <a href="https://tncvoicechoiceaction.org/" target="_blank" rel="noopener noreferer">
                VCA
              </a>
              , which describes the kinds of relationships that conservation organizations aim to
              have with IPLCs — affirming their right to self-determination;
            </li>
            <li>
              To help teams follow{" "}
              <a
                href="https://www.tnchumanrightsguide.org/"
                target="_blank"
                rel="noopener noreferer"
              >
                the principles of the Guide
              </a>
              , which describes how to achieve those relationships through Free, Prior, and Informed
              Consent.
            </li>
          </ol>

          <p>
            The VCA and the Guide focus on principles and process more than on particular human
            rights because human rights cannot be limited to a single perspective.
          </p>

          <p>
            Understanding the human rights issues presented by a project in the context of
            established international human rights law is an important step — especially for work
            convened by multinational organizations. Many organizations are members of the
            Conservation Initiative on Human Rights, a consortium of international organizations
            that seek to improve conservation practices by promoting human rights in policies and
            practices.
          </p>

          <ul>
            <li>
              For more on respect for human rights:
              <ul>
                <li>
                  <a
                    href="https://tncvoicechoiceaction.org/foundational-elements/foundational-element-1-equitable-benefits-impacts-and-inclusion/"
                    target="_blank"
                    rel="noopener noreferer"
                  >
                    VCA Foundational Element 1 - Equitable Benefits, Impacts, and Inclusion
                  </a>
                </li>
              </ul>
            </li>
            <li>
              For more on how to achieve detailed human rights analysis:
              <ul>
                <li>
                  <a
                    href="https://www.tnchumanrightsguide.org/module-2-free-prior-informed-consent/#human-rights-impact-assessment"
                    target="_blank"
                    rel="noopener noreferer"
                  >
                    The FPIC process
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.tnchumanrightsguide.org/module-4-implementation/#step-one"
                    target="_blank"
                    rel="noopener noreferer"
                  >
                    Implementation
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.tnchumanrightsguide.org/module-6-monitoring-evaluation-adaptation/#step-one"
                    target="_blank"
                    rel="noopener noreferer"
                  >
                    Monitoring, Evaluation, and Adaptation
                  </a>
                </li>
              </ul>
            </li>
          </ul>

          <p>
            A template of human rights indicators can be found in the Guide, but there is no human
            rights screening process. This Tool aims to fill that gap.
          </p>

          <p>The below chart shows connections between the Tool, the VCA, and the Guide.</p>

          <h2>What “Communities” Means in Screening Contexts</h2>

          <p>
            The term IPLC is understood to include all “peoples and communities who possess a
            profound relationship with their natural landscapes, which they depend on for cultural,
            spiritual, economic and physical well-being.” See Guide, Module 1(11).
          </p>

          <p>
            An even broader view of IPLCs — called “Communities” in this Tool — is appropriate for
            preliminary screening.
          </p>

          <p>
            This Tool stops short of guiding teams toward reaching policy outcomes or resolving
            competing claims. The work of the Tool is to identify issues and prioritize them in
            lists. Thus, a broad and inclusive approach is needed.
          </p>

          <p>
            In practice, this means that teams should avoid trying to assess the relative profundity
            of a community’s connection to its lands, because these questions typically raise
            complications and potential missteps.
          </p>

          <p>
            The use of “Communities” errs on the side of greatest inclusion. Any community that
            purports to have a relationship to the landscape may be included — fishers, farmers,
            others — and a more closely delineated definition may occur in later processes.
          </p>

          <p>
            A few indicators require careful attention to the question of whether given Communities
            are recognized by international law as Indigenous Peoples.
          </p>

          <p>
            The UNDRIP does not provide a fixed definition of “Indigenous Peoples,” recognizing that
            such definitions have historically been used to exclude Indigenous Peoples from
            recognition, rights, and benefits.
          </p>

          <p>
            Respect for community self-definition and self-determination leads to better
            relationships and more sustainable conservation outcomes alike.
          </p>

          <p>
            For more, see{" "}
            <a
              href="https://www.un.org/esa/socdev/unpfii/documents/5session_factsheet1.pdf"
              target="_blank"
              rel="noopener noreferer"
            >
              Who Are Indigenous Peoples?
            </a>
            , UN Permanent Forum on Indigenous Issues.
          </p>

          <h2>Communities and the Screening Process</h2>
          <p>How should teams bring Communities into the screening process?</p>
          <p>It is a difficult question with a nuanced answer.</p>
          <p>
            Firstly, Communities themselves are the most important and accurate source of
            information about their own interests. It’s essential to bring them into any risk
            assessment process prior to making any major decisions about implementation or
            mitigation.
          </p>
          <p>But timing is important.</p>
          <p>
            In many cases, it is unfair to impose the burden of screening work on Communities. It is
            the business or organization’s responsibility to ensure its work does not cause human
            rights impacts. It is not the Communities’ responsibility to help a business or
            organization assess itself, and there should be no expectation of this labor, and
            certainly not without fair compensation.
          </p>
          <p>
            The screening processes of this Tool are a preliminary exercise in identifying issues,
            prioritizing them, and organizing teams’ thinking. It is an introduction pointing toward
            ways to begin a collaborative process with Communities.
          </p>
          <p>
            The Tool is not a one-stop shop for completing human rights due diligence or process for
            community engagement.
          </p>
          <p>Conservation teams have two equally important responsibilities:</p>
          <ol>
            <li>
              Conduct their own screening process to determine any human rights impacts they might
              have;
            </li>
            <li>
              Follow up and validate its impressions with Communities during later engagement.
            </li>
          </ol>

          <p>
            Teams should rely on their local knowledge and experience. And they should also know —
            and be candid about — the limits of their knowledge. The Tool will help by recommending
            areas for further research before decisions are made.
          </p>
          <p>
            Only <strong>after</strong> the screening process is complete should teams begin to
            develop concrete plans and problem-solve.
          </p>
          <p>
            During the Research Phase detailed in the next section, teams should gain familiarity
            with the region’s Communities and relevant issues. After that, the screening process can
            begin.
          </p>
          <p>
            It’s recommended to do the work of planning and problem-solving in concert with
            Communities. At this phase, teams should validate the determinations of the screening
            process as well.
          </p>
          <p>
            See also FAQ: Why are teams doing this analysis themselves instead of hiring an expert?
          </p>
          <p>
            While teams are responsible for preliminary screening, this does not invalidate the
            importance of early engagement with communities to ensure respect for human rights and
            self-determination.
          </p>
          <p>
            As the{" "}
            <a
              href="https://www.tnchumanrightsguide.org/module-1-learning-early-discussions/"
              target="_blank"
              rel="noopener noreferer"
            >
              Guide
            </a>{" "}
            describes, no concept development should begin before Communities are engaged. Careful
            planning and practicing restraint will help teams adhere to this mandate.
          </p>

          <p>
            Early engagement with Communities is fundamental in international human rights law. It
            is required by courts.
          </p>
          <p>
            Given historical power imbalances, Communities may be reluctant to raise issues or
            insert their perspectives if it feels like major decisions have already been decided.
          </p>
          <p>
            If Communities are made to feel they have been brought in to rubber-stamp something
            that’s already been decided, the relationship suffers, along with the outcome.
          </p>
          <p>
            Furthermore, Communities almost always hold critical details about which strategies or
            approaches will work.
          </p>
          <p>
            To the extent that a business or organization and Communities have different goals, a
            shared set of goals should be established. Businesses and organizations should not
            attempt to force Communities’ goals into a project not designed to meet their needs.
          </p>

          <h2>Learning & Early Discussions</h2>
          <p>
            In preparing to use this Tool, teams should feel empowered to conduct research and
            engage with key Communities.{" "}
            <a
              href="https://www.tnchumanrightsguide.org/module-1-learning-early-discussions/"
              target="_blank"
              rel="noopener noreferer"
            >
              Module 1 of the Human Rights Guide
            </a>{" "}
            might help guide you to identify Communities, assess your capacity for engaging, and
            focus on how to engage respectfully. Human rights often are and should be adapted to
            local understandings and values. Outsiders must bring humility and deference to the
            process of applying their understanding of “international human rights” to other
            peoples’ circumstances.
          </p>
          <h2>Project and Community Background</h2>
          <p>
            Teams should complete a stakeholder mapping or interested parties assessment to identify
            rightsholders and uncover all the potential impacts that affect them. They should also
            identify subgroups within Communities who might need special human rights
            considerations. Addtionally in this phase, the tool generates the following
            project-specific terms:
          </p>
          <ul>
            <li>Project Site</li>
            <li>Project Area</li>
            <li>Project Region</li>
          </ul>
          <p>
            The real utility of the research phase is to help teams familiarize themselves with the
            geographies, Communities, and other contexts present in a project. There are many{" "}
            <Link href="/other-tools" target="_blank" rel="noopener noreferer">
              other context-setting tools
            </Link>{" "}
            available for this work, so teams should decide for themselves which one suits best.
          </p>
          <h2>Screening Phase</h2>
          <h3>Human Rights Risk</h3>
          <p>
            Conservation work creates impacts. These impacts can be good or controversial, or indeed
            hard to characterize. Running a livelihoods program carries the risk of unfavorable
            results, impacting gender equity, or impacting a Community’s right to
            self-determination.
          </p>
          <p>
            It’s important to be aware of this possibility in order to avoid unfavorable outcomes.
            Human-rights based conservation seeks to respect and advance human rights, and as such,
            we see risks as inevitable and embrace the process of identifying risk and responding
            well to it. This Tool helps identify and prioritize those risks.
          </p>
          <p>
            The scope of human rights and our responsibility to respect and caretake them is vast,
            so understanding how actions and impacts are linked well help teams understand TNC’s
            obligations. This Tool was designed to identify and prioritize human rights risks — it
            answers to broad ranges of impacts, including not only severe human rights abuses but
            also socioeconomic rights, labor rights, and complex collective rights like the right to
            self-determination.
          </p>
          <p>
            Following a comprehensive{" "}
            <Link
              href="/glossary#human-rights-due-diligence"
              target="_blank"
              rel="noopener noreferer"
            >
              human rights due diligence process (HRDD)
            </Link>{" "}
            is essential. The responsibility of HRDD is to first identify and assess risk, and
            secondly to co-create, implement, and review mitigation strategies. This Tool applies
            these concepts by way of the Project Risk Determination Framework.
          </p>
          <h3>Contextual Risk and Project Risk</h3>
          <p>The screening phase comprises two distinct parts:</p>
          <ol>
            <li>Contextual Risk Screen: Assessment of the overall environment</li>
            <li>Project Risk Screen: Focusing on the specific project and its likely impacts</li>
          </ol>
          <p>
            The overall environmental assessment is performed with the framework of the Contextual
            Risk Screen. It can be easy to overlook human rights risks, especially when supporters
            are optimistically focused on benefits and upsides as opposed to unexpected turns of
            events.
          </p>
          <p>
            Importantly, because the Contextual Risk Screen casts such a broad lens, it presumes
            that any risks that are uncovered will be linked to the project in question, unless the
            team specifically determines that a risk is not applicable, unlikely, or already has a
            mitigation strategy in place.
          </p>
          <p>
            This first phase of the screening process moves quickly, as its indicators identify
            rights issues broadly and asks whether Communities working in the area are aware of
            them.&nbsp;Teams can answer &ldquo;yes,&rdquo; &ldquo;no,&rdquo; or &ldquo;need for more
            research,&rdquo; the latter of which puts the indicator on a Research List for teams to
            document and organize issues for investigation.
          </p>
          <p>
            A more in-depth analysis is performed with the Project Risk Screen, which zooms in on
            indicators identified in the Contextual screening process. At this level, teams will be
            given indicator-specific guidance and cross-references to other indicators and tools,
            moving on to a more structured assessment in the Project Risk Determination, where each
            indicator will be placed into one of three categories:
          </p>
          <ul>
            <li>Escalate List</li>
            <li>Prioritize List</li>
            <li>Watch List</li>
          </ul>
          <h3>Judgment and Prioritization</h3>
          <p>
            Human rights screening is a complex process, requiring existing knowledge, experience,
            and keen attunement. It can be difficult to make judgment calls or know how to
            prioritize, but it&rsquo;s a necessary part of the process, because after all, if
            everything is a priority, nothing is a priority.
          </p>
          <p>
            This Tool, with its planned and prescriptive structure, aims to cut down on the
            cognitive load required to do this prioritization effectively. It will organize
            teams&rsquo; thinking so they can usefully engage with Communities, but it is not a
            one-stop shop. Rather, the Tool itself expressly guides teams to revisit and validate
            determinations with the Communities.
          </p>
          <p>
            During some of our early workshopping of this Tool, teams felt uncomfortable making risk
            determinations, particularly if they felt they would be on the hook for missing
            something.
          </p>
          <p>This is understandable.</p>
          <p>
            It&rsquo;s important to remember that, if no due diligence process like this is
            followed, the team is essentially making a &ldquo;no risk&rdquo; determination about
            everything. Therefore it&rsquo;s better to follow a process, however imperfect or
            incomplete it might feel.
          </p>
          <p>
            With that in mind, team members should be made to feel comfortable engaging with the
            Tool and properly incentivized to identify risks, even if their identification might
            delay project deadlines.
          </p>
          <p>
            In our workshopping sessions, team members became more comfortable with making these
            judgments as they familiarized themselves with the Tool. And the discussions that ensued
            from engaging with the Tool were found to be educational and clarifying.
          </p>
          <h3>Key Tool: The Project Risk Determination</h3>
          <p>
            This risk analysis framework, then, is meant to help teams determine whether an
            identified risk can be considered limited or manageable to the point that it is a normal
            part of work in the environment.
          </p>
          <p>
            That’s not to say these risks are ignored, but they are placed on the Watch List, where
            they receive a different level of attention.
          </p>
          <p>A useful acronym to remember the elements of a so-called “normal” risk is NAURMAL:</p>
          <ul>
            <li>
              <b>NA</b> —{" "}
              <b>
                <u>N</u>
              </b>
              ot{" "}
              <b>
                <u>A</u>
              </b>
              pplicable to the project
            </li>
            <li>
              <b>U</b> —{" "}
              <b>
                <u>U</u>
              </b>
              nlikely to occur
            </li>
            <li>
              <b>RM</b> —{" "}
              <b>
                <u>R</u>
              </b>
              eliable{" "}
              <b>
                <u>M</u>
              </b>
              itigation strategies exist and are
            </li>
            <li>
              <b>A</b> —{" "}
              <b>
                <u>A</u>
              </b>
              vailable
            </li>
            <li>
              <b>L</b> —{" "}
              <b>
                <u>L</u>
              </b>
              imited scope of risk
            </li>
          </ul>
          <p>
            Having learned from our past workshopping process, we hope this tool will help teams to
            feel more comfortable making the complex risk analysis decisions required at this phase
            of engagement.
          </p>
          <p>
            The Project Risk Determination is meant to give teams a high-level impression of where a
            given risk falls on the continuum of project risk. Teams then use that, along with
            indicator-specific guidance, to place risks on the Escalate, Priority, or Watch Lists.
          </p>
          <h3>Key Tool: Minimum Core Risk Determination</h3>
          <p>
            Minimum Core Risk Determinations apply most often to socioeconomic rights: food, water,
            housing, education, medical care, and so on, as delineated further in this helpful{" "}
            <a
              href="https://www.ohchr.org/sites/default/files/documents/publications/factsheet33en.pdf"
              target="_blank"
              rel="noopener noreferer"
            >
              fact sheet
            </a>
            . These rights are understood somewhat differently than civil and political rights.
            Rather than setting concrete standards, these rights are seen as imposing obligations on
            states to{" "}
            <Link href="/glossary#progressive-realization" target="_blank">
              “progressively realize”
            </Link>{" "}
            the right over time. That said, socioeconomic rights have a “minimum core,” the
            violation of which is a violation of human rights law like any other. The factors that
            indicate a minimum core violation include
          </p>
          <ol>
            <li>Unlawful discrimination in respecting, protecting, or fulfilling the right</li>
            <li>Retrogressive action measures that worsen baseline conditions</li>
            <li>
              Failing to pursue available mitigation strategies that would alleviate insecurity
            </li>
            <li>
              The existence of persistent severe inadequacies, particularly those that affect
              children.
            </li>
          </ol>
          <p>
            These factors are described in more detail in the Minimum Core Risk Determination
            Framework. When directed in the Project Risk Screen,, teams should apply factors (A)-(D)
            above and determine if a project risks violating Communities’ minimum core enjoyment of
            a right.
          </p>
          <h3>The Research List</h3>
          <p>
            While performing the Contextual Risk Screen, teams may find some indicators that require
            more information to mark as a contextual risk. These are to be pursued with desk
            research in tandem with preliminary Community engagement as outlined in{" "}
            <a
              href="https://www.tnchumanrightsguide.org/module-1-learning-early-discussions/"
              target="_blank"
              rel="noopener noreferer"
            >
              Module 1 of the Human Rights Guide
            </a>
            .
          </p>
          <h3>The Escalate List</h3>
          <p>
            In cases where risks are considered severe, “grave,” or “gross” violations in
            international human rights law, and irrespective of whether they are more or less likely
            to occur, organizations like TNC have a stronger obligation to avoid these risks.
            Mitigation strategies might be deemed unreliable in the face of these risks, as they
            might be accompanied by a breakdown in governance or other types of protections. Such
            risks are placed on the Escalate List.
          </p>
          <p>
            Risks marked on the Escalate List should receive follow up via the process described
            below. A risk on the Escalate List might still be a viable project, but it should be put
            on hold and vetted by reviewers outside the project team who might have specialized
            expertise in human rights and risk analysis.
          </p>
          <p>
            If a project is already in motion, the action of putting it on hold might itself trigger
            adverse human rights impacts. In those circumstances, do suspend significant changes or
            expansions until the risk is reviewed.
          </p>
          <p>
            The additional layer of review is still being piloted, and is described below. If an
            Escalate List risk has already been examined by regional, national, or global leadership
            outside the project team, the Tool recommends a refresh.
          </p>
          <blockquote>
            Note: This Tool aligns with TNC’s heightened risk definition, as it identifies conflicts
            with TNC’s core values and general adverse impacts. That will necessitate performing a{" "}
            <a
              href="https://thenatureconservancy462.sharepoint.com/sites/Department/rac/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDepartment%2Frac%2FShared%20Documents%2FHeightened%20Risk%20Guidelines%2Epdf&parent=%2Fsites%2FDepartment%2Frac%2FShared%20Documents"
              target="_blank"
              rel="noopener noreferer"
            >
              heightened risk analysis
            </a>{" "}
            as described by TNC. The Tool also serves to identify heightened people risk assessment
            factors, and it helps create social safeguards and recommendations.
          </blockquote>

          <h3>The Prioritize List</h3>
          <p>
            Some risks, on the other hand, need to be prioritized for prompt attention by project
            teams and incorporated into the project design and implementation processes.
          </p>
          <p>
            There is a natural tendency to over-include priorities to avoid making a mistake, but as
            stated above, if everything is a priority, nothing is a priority. This Tool will help
            with these priority decisions with specific guidance and key risk analysis frameworks.
          </p>
          <p>
            When a risk carries a high level of project risk that does not fall under the Escalate
            category, it will be placed on the Prioritize List for prompt attention by the project
            team. All other risks, assessed by the Project Risk Determination template, will be
            placed on the Watch List. Leaving these off the Prioritize List frees up time and
            resources to address the most urgent issues.
          </p>
          <p>
            The recommended follow up for issues on the prioritize list is described below, and
            includes engagement and collaboration with Communities and rightsholders and potentially
            a human rights expert.
          </p>

          <h3>The Watch List</h3>

          <p>
            The Watch List is a holding space for contextual risks that aren’t top priorities,
            whether because of timing, because of situations that are uncertain and evolving.
            Remember that not everything can be a top priority. These risks should be revisited and
            reassessed regularly — no less than once a year.
          </p>

          <p>
            The Watch List is also helpful to revisit at the implementation phase, or when designing
            Community engagement processes.
          </p>

          <p>
            Some items on the Watch List might be better addressed with alternative tools. The range
            of human rights considered by this Tool is broad — food, water, housing, medical care,
            education, standards of living, collective rights, inter-generational rights. The
            correct approach to the social challenges underlying each of these rights is still under
            debate, and approaches that are comprehensive and correct in one context might not work
            in other contexts. A global toolkit is useful, but it is not a global substitute
            purporting to work in every situation. Other approaches that are more flexible or
            locally adapted should be considered and assessed.
          </p>

          <p>
            Cross referencing to{" "}
            <Link href="/other-tools" target="_blank">
              Other Tools
            </Link>{" "}
            enables teams to off-ramp some risks into different solution frameworks. These risks are
            still included on the Watch List so that teams can easily review progress and maintain a
            single point of reference for risks. Risks on the Watch List can occasionally be
            reviewed using the Minimum Core Risk Determination Framework to ensure that no unlawful
            discrimination occurs that would violate the minimum core of the right in question.
          </p>

          <h3>Results Tables</h3>

          <p>
            Summary information is pulled from the screening process and codified into the Escalate,
            Prioritize, and Watch Lists. These results tables are designed to help organize action
            and recommendations for teams to pursue.
          </p>

          <p>
            There is potential for items on these lists to overlap. Project teams are expected to
            use their discretion to set priorities and schedule analyses and check-ins at various
            stages of project design and implementation. This should ensure transparency and
            accountability, while also prioritizing the expertise of local management from
            Communities.
          </p>

          <h2>Follow-up Phase</h2>
          <h3>Escalate List Follow-up: Seek Additional Review</h3>
          <p>
            Because issues on the Escalate List often reflect governance or social breakdown, they
            are unpredictable, difficult to mitigate, and carry a high degree of human rights and
            organizational risk. Therefore, decisions cannot be made with the project team alone;
            TNC leadership and outside experts should be consulted.
          </p>
          <p>
            There is, as yet, no specific review process to follow for Escalate List risks. Future
            options could include use of existing review committees, a new specialized review
            committee, or selected staff who have knowledge of the risks in question. Higher-level
            reviewers should be able to:
          </p>
          <ul>
            <li>Exercise independent judgment</li>
            <li>
              Offer expertise in human rights and/or the challenges of the particular project
              environment
            </li>
            <li>
              Oversee discretionary budget with authority to direct additional research or engage
              outside experts
            </li>
            <li>
              Assess organizational risk to TNC, TNC’s partners, and the NCS community of practice
              globally
            </li>
          </ul>
          <p>
            For beta users of the Tool, the interim process is to send their Escalate List results
            to their Business Unit or Regional Leadership for review. Reviewers will have support
            from a specialized TNC legal advisor who will assist reviewers in determining next steps
            and escalating the issue to existing review mechanisms if there is an urgent need to do
            so.
          </p>
          <p>
            If Escalate List risks have previously been examined by higher-level leadership, as in
            the case of ongoing projects, the review need not start over from scratch. A general
            guideline is for leadership to refresh its formal review of these risks every two years
            by way of a written analysis that reconsiders mitigation strategies in light of new
            developments.
          </p>
          <p>
            Additionally, teams can use the summary information on key risk assessment criteria to
            conduct less formal reviews on a more regular basis, sharing it with colleagues on other
            teams and units.
          </p>

          <h3>
            Prioritize List Follow-up: Use a Rightsholder Engagement Tool or Other Due Diligence
          </h3>

          <p>
            Following the screening, teams should address risks on the Prioritize List by engaging
            with rightsholders and other interested parties. A forthcoming component of this toolset
            (tentatively called the Rightsholder Engagement Tool) will help teams facilitate the
            sometimes complex and difficult conversations about:
          </p>
          <ol>
            <li>What the relevant human rights issues are, </li>
            <li>
              What the corresponding actions and obligations are (e.g., for the government, for TNC,
              for others), and{" "}
            </li>
            <li>
              What can and should be done to avoid or mitigate the risk or human rights violations.{" "}
            </li>
          </ol>
          <p>
            Both the Screening Tool and the forthcoming Rightsholder Engagement Tool are components
            of the larger process of Human Rights Due Diligence.
          </p>
          <p>
            HRDD is an increasingly important and rapidly evolving international standard, with new
            expectations emerging from national laws and institutional best practice. It is
            typically understood to include not just identifying and assessing risks, but also a
            process of engaging rightsholders on risks and implementing prevention and mitigation
            actions. The Screening Tool helps teams fulfill the identification and assessment part
            of the process. The Rightsholder Engagement Tool helps teams fulfill the engagement
            component and lays a foundation for collaborative creation of mitigation strategies.
            This is a particularly necessary step given that the screening is primarily based on the
            teams’ own knowledge and perspective.
          </p>
          <p>
            Teams can also review the{" "}
            <a
              href="https://www.tnchumanrightsguide.org/module-4-implementation/"
              target="_blank"
              rel="noopener noreferer"
            >
              Human Rights Guide, Module 4
            </a>{" "}
            for more comprehensive guidance on how the dialogue should proceed in order to reach
            consensus.
          </p>

          <h3>Watch List Follow-up: Engage, Monitor, and Periodic Review</h3>
          <p>Entries on the Watch List fall into one of two categories:</p>
          <ol>
            <li>Risks from the Contextual Screen that were deemed to be low Project Risks</li>
            <li>
              Equity and well-being considerations that may be better addressed using other
              approaches
            </li>
          </ol>

          <p>
            Project Risks deemed low-risk in the Project Risk Screen still are present in the
            operating environment. Thus, they might exert continued pressure on the project, and
            further links to the project could be revealed as it grows, succeeds, fails, and/or
            gains public awareness. Therefore, teams should review these risks annually.
          </p>

          <p>
            Likewise, equity and well-being considerations should be reviewed once a year, along
            with the status or latest updates of any other tools or frameworks that have been used
            to explore or approach the issue.
          </p>

          <p>
            The Watch List should be considered a background resource for Community engagement and
            project implementation. Every item on the list is worth discussing with Communities and
            decision-making partners as implementation decisions approach.
          </p>

          <p>
            Community input should be sought to help teams understand on-the-ground relevance of the
            risks identified through the screening process and inform decisions. Where Communities
            raise different points of view, teams should:
          </p>

          <ul>
            <li>
              Always listen for allegations about issues that were previously determined not to be
              contextual risks, and add them to one of the lists.
            </li>
            <li>
              Consider removing any risks from the Watch List that Communities say are not{" "}
              <Link href="/glossary#salient" target="_blank">
                salient
              </Link>
              .
            </li>
            <li>
              Elevate items to the Prioritize List if risk seems heightened or perceived mitigation
              strategies aren’t reliable or available.
            </li>
            <li>
              Use the Project Risk Screen to assess any new risks that are identified from community
              discussions, and apply the Project Risk Determination to add risks to the Escalate
              List (if a Minimum Core Violation exists), Prioritize List, or Watch List as
              applicable.
            </li>
          </ul>

          <h3>Quick Look Option</h3>
          <p>
            If a project team is facing a time sensitive demand for human rights screening and is
            not ready to engage the full Screening Tool, they can consider the following options:
          </p>

          <ol>
            <li>
              There are several “yes/no” or “high/medium/low” checklists in development that list
              human rights issues associated with conservation and development projects. While these
              lists have less guidance on prioritization, linkage, or illustration of common issues,
              they may be useful as an overview, to help ensure that clear issues are not somehow
              overlooked, or for compliance purposes. Future versions of this tool will include a
              list of useful checklists.
            </li>
            <li>
              This Screening Tool can be used in a checklist/overview fashion by reviewing questions
              or indicators in the Contextual Risk Screen, or even more simply by reviewing the
              indicator headings in the Quick List of Indicators, below. If there is any difficulty
              in answering an Indicator, teams can look to any guidance available in the Project
              Risk Screen on an indicator-by-indicator basis.
            </li>
            <li>
              Finally, teams working on carbon projects can examine their project in light of the
              Carbon Project Controversies section of the Research Phase. This contains a list of
              common issues and controversies surrounding carbon projects over the last few years.
              While there is no specific guidance contained herein, it is useful to stimulate
              discussion and identify issues.
            </li>
          </ol>
        </div>
      </div>

      <div className="col-span-12 sm:col-span-8 lg:col-span-4">
        <Card className="sticky top-10">
          <CardHeader className="prose w-full">
            <CardTitle>Research phase</CardTitle>
          </CardHeader>
          <CardContent className="prose w-full">
            <p>
              The research phase is the first step in the process of using the Human Rights
              Screening Tool
            </p>
            <Link
              href={`/projects/${params.id}/project-and-background-community`}
              className="block"
            >
              <Button size="lg" className="w-full">
                Get started
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
